import { PrismaClient } from "@prisma/client"
import { createAuditExtension } from "./prisma-audit"

const prismaClientSingleton = () => {

    const client = new PrismaClient()

    return client.$extends(createAuditExtension(client))
}

declare global {
    var prismaGlobal: undefined | ReturnType<typeof prismaClientSingleton>
}

export const prisma =
    globalThis.prismaGlobal ?? prismaClientSingleton()

if (process.env.NODE_ENV !== "production") {
    globalThis.prismaGlobal = prisma
}

/**
 * This captures the exact type of specific extended client
 */
export type ExtendedPrismaClient = typeof prisma;

/**
 * This captures the type of the transaction client generated by extended client
 */
export type ExtendedTransactionClient = Parameters<Parameters<ExtendedPrismaClient["$transaction"]>[0]>[0];

/**
 * A union type for your services: "Either the full extended client or its transaction"
 */
export type DB = ExtendedPrismaClient | ExtendedTransactionClient;