"use client"

import { useState } from "react"
import {
    Sparkles,
    Copy,
    Download,
    RefreshCw,
    Bell,
    FileText,
    Share2,
    ShieldAlert,
} from "lucide-react"

import { Sidebar } from "@/components/users-ui/dashboard/Sidebar"
import { Header } from "@/components/users-ui/dashboard/Header"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"

export default function ContentGeneratorPage() {
    const [isCollapsed, setIsCollapsed] = useState(false)

    const [contentType, setContentType] = useState("")
    const [tone, setTone] = useState("")
    const [selectedTemplate, setSelectedTemplate] = useState("")

    const [location, setLocation] = useState("")
    const [aqi, setAqi] = useState("")
    const [pollutants, setPollutants] = useState("")
    const [details, setDetails] = useState("")

    const [generatedContent, setGeneratedContent] = useState("")

    const templates = [
        {
            icon: Bell,
            title: "AQI Alert Message",
            description: "Generate AQI warning alerts",
            tone: "Warning",
            type: "Alert",
        },
        {
            icon: FileText,
            title: "Air Quality Article",
            description: "Create AQI blog content",
            tone: "Informative",
            type: "Article",
        },
        {
            icon: Share2,
            title: "AQI Social Post",
            description: "Generate social media posts",
            tone: "Friendly",
            type: "Social Post",
        },
        {
            icon: ShieldAlert,
            title: "Health Advisory",
            description: "Write safety recommendations",
            tone: "Serious",
            type: "Advisory",
        },
    ]

    const handleTemplateClick = (template: any) => {
        setSelectedTemplate(template.title)
        setTone(template.tone)
        setContentType(template.type)
    }

    const generateAQIContent = () => {
        const aqiNumber = Number(aqi)

        let level = "Good"
        let advice =
            "Air quality is good. Enjoy outdoor activities normally."

        if (aqiNumber >= 51 && aqiNumber <= 100) {
            level = "Moderate"
            advice =
                "Sensitive individuals should consider reducing prolonged outdoor exertion."
        } else if (aqiNumber >= 101 && aqiNumber <= 150) {
            level = "Unhealthy for Sensitive Groups"
            advice =
                "People with asthma or heart conditions should limit outdoor activity."
        } else if (aqiNumber >= 151 && aqiNumber <= 200) {
            level = "Unhealthy"
            advice =
                "Avoid outdoor exercise. Wear a mask if going outside."
        } else if (aqiNumber >= 201 && aqiNumber <= 300) {
            level = "Very Unhealthy"
            advice =
                "Stay indoors as much as possible. Use air purifiers and avoid exposure."
        } else if (aqiNumber > 300) {
            level = "Hazardous"
            advice =
                "Health warning: Stay indoors. Avoid all outdoor activities."
        }

        const content = `
📍 Location: ${location || "Unknown Location"}
🌫️ AQI: ${aqi || "N/A"} (${level})
🧪 Pollutants: ${pollutants || "PM2.5 / PM10"}

📝 Content Type: ${contentType || "AQI Update"}
🎯 Tone: ${tone || "Neutral"}

⚠️ Advisory:
${advice}

${details ? `📌 Additional Notes:\n${details}\n` : ""}

Generated by a2aqi.com AI Content Generator.
`.trim()

        setGeneratedContent(content)
    }

    const handleCopy = async () => {
        if (!generatedContent) return
        await navigator.clipboard.writeText(generatedContent)
    }

    const handleReset = () => {
        setGeneratedContent("")
    }

    return (
        <div className="flex min-h-screen bg-background">
            <div className="hidden lg:block">
                <Sidebar isCollapsed={isCollapsed} onToggle={() => setIsCollapsed(!isCollapsed)} />
            </div>

            <main className={cn(
                "flex-1 p-4 md:p-5 lg:p-6 transition-all duration-300 px-4",
                isCollapsed ? "lg:ml-16" : "lg:ml-60",
            )}>
                <Header
                    title="AQI Content Generator"
                    description="Generate AQI alerts, air quality reports, and health advisory content for a2aqi.com."
                    actions={
                        <Button
                            onClick={generateAQIContent}
                            className="w-full sm:w-auto h-9 text-sm bg-gradient-to-r from-primary to-accent text-primary-foreground hover:opacity-90 transition-all duration-300 hover:shadow-lg hover:shadow-primary/30 hover:scale-105"
                        >
                            <Sparkles className="w-4 h-4 mr-2" />
                            Generate Content
                        </Button>
                    }
                />

                <div className="mt-4 md:mt-5 space-y-3 md:space-y-4">
                    {/* Templates */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
                        {templates.map((template, index) => (
                            <Card
                                key={index}
                                onClick={() => handleTemplateClick(template)}
                                className={`p-4 hover:shadow-lg transition-all duration-300 cursor-pointer hover:scale-[1.02] bg-card border-border ${selectedTemplate === template.title ? "ring-2 ring-primary" : ""
                                    }`}
                            >
                                <div className="flex flex-col items-center text-center gap-3">
                                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                                        <template.icon className="w-6 h-6 text-primary-foreground" />
                                    </div>

                                    <div>
                                        <h3 className="font-semibold text-foreground">{template.title}</h3>
                                        <p className="text-xs text-muted-foreground mt-1">{template.description}</p>
                                    </div>
                                </div>
                            </Card>
                        ))}
                    </div>

                    {/* Input + Output */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 md:gap-4">
                        {/* Input */}
                        <Card className="p-4 md:p-6 bg-card border-border">
                            <h2 className="text-lg font-semibold text-foreground mb-4">Input</h2>

                            <div className="space-y-4">
                                <div>
                                    <Label className="text-sm font-medium text-foreground">Content Type</Label>
                                    <Input
                                        value={contentType}
                                        onChange={(e) => setContentType(e.target.value)}
                                        placeholder="Select a template..."
                                        className="mt-1.5 bg-background border-border"
                                    />
                                </div>

                                <div>
                                    <Label className="text-sm font-medium text-foreground">Tone</Label>
                                    <Input
                                        value={tone}
                                        onChange={(e) => setTone(e.target.value)}
                                        placeholder="Select a template..."
                                        className="mt-1.5 bg-background border-border"
                                    />
                                </div>

                                <div>
                                    <Label className="text-sm font-medium text-foreground">Location / City</Label>
                                    <Input
                                        value={location}
                                        onChange={(e) => setLocation(e.target.value)}
                                        placeholder="e.g., Delhi, Mumbai"
                                        className="mt-1.5 bg-background border-border"
                                    />
                                </div>

                                <div>
                                    <Label className="text-sm font-medium text-foreground">AQI Value</Label>
                                    <Input
                                        value={aqi}
                                        onChange={(e) => setAqi(e.target.value)}
                                        placeholder="e.g., 165"
                                        className="mt-1.5 bg-background border-border"
                                    />
                                </div>

                                <div>
                                    <Label className="text-sm font-medium text-foreground">Main Pollutants</Label>
                                    <Input
                                        value={pollutants}
                                        onChange={(e) => setPollutants(e.target.value)}
                                        placeholder="e.g., PM2.5, PM10, NO2"
                                        className="mt-1.5 bg-background border-border"
                                    />
                                </div>

                                <div>
                                    <Label className="text-sm font-medium text-foreground">Additional Details</Label>
                                    <Textarea
                                        value={details}
                                        onChange={(e) => setDetails(e.target.value)}
                                        placeholder="Example: recommend mask usage, avoid outdoor exercise..."
                                        className="mt-1.5 bg-background border-border min-h-[120px]"
                                    />
                                </div>

                                <Button
                                    onClick={generateAQIContent}
                                    className="w-full bg-gradient-to-r from-primary to-accent text-primary-foreground hover:opacity-90"
                                >
                                    <Sparkles className="w-4 h-4 mr-2" />
                                    Generate AQI Content
                                </Button>
                            </div>
                        </Card>

                        {/* Output */}
                        <Card className="p-4 md:p-6 bg-card border-border">
                            <div className="flex items-center justify-between mb-4">
                                <h2 className="text-lg font-semibold text-foreground">Generated Content</h2>

                                <div className="flex gap-2">
                                    <Button onClick={handleReset} variant="ghost" size="icon" className="h-8 w-8 bg-transparent">
                                        <RefreshCw className="w-4 h-4" />
                                    </Button>

                                    <Button onClick={handleCopy} variant="ghost" size="icon" className="h-8 w-8 bg-transparent">
                                        <Copy className="w-4 h-4" />
                                    </Button>

                                    <Button variant="ghost" size="icon" className="h-8 w-8 bg-transparent">
                                        <Download className="w-4 h-4" />
                                    </Button>
                                </div>
                            </div>

                            <div className="bg-muted rounded-lg p-4 min-h-[400px] text-sm text-foreground leading-relaxed whitespace-pre-line">
                                {generatedContent ? (
                                    generatedContent
                                ) : (
                                    <p className="text-muted-foreground italic">
                                        Your AQI-based content will appear here. Select a template, enter details, and click Generate.
                                    </p>
                                )}
                            </div>
                        </Card>
                    </div>
                </div>
            </main>
        </div>
    )
}
