export const SENSORUNIT: Record<string, string> = {
    Aqi: "",
    Pm10: "µg/m³",
    Pm25: "µg/m³",
    So2: "ppb",
    No2: "ppb",
    Co2: "ppm",
    Co: "ppm",
    O3: "ppb",
    Noise: "dB",
    PM1: "µg/m³",
    Tvoc: "ppb",
    Smoke: "ppm",
    Methane: "ppm",
    H2: "ppm",
    Ammonia: "ppm",
    H2s: "ppm",
    Temperature: "°C",
    Humidity: "%",
}